import type { getOctokit } from "@actions/github";

type Octokit = ReturnType<typeof getOctokit>;

// Hidden marker so we can find and update our own comment instead of
// spamming a new one on every push to the PR.
export const ARCHLENS_MARKER = "<!-- archlens-ai-comment -->";

export function buildCommentBody(params: {
  svgUrl: string;
  mermaidSource: string;
  diagramType: string;
  truncated: boolean;
  repoFullName: string;
  prNumber?: number;
  filesMatched?: number;
}): string {
  const truncatedNote = params.truncated
    ? "\n\n> ⚠️ This diff was larger than the configured size cap — the diagram reflects the largest structural changes, not every file.\n"
    : "";

  // Disclosed, not hidden: past ~6 matched files, Mermaid's own layout
  // engine starts crossing edges through unrelated nodes and losing
  // subgraph containment (a confirmed, unresolved limitation — see
  // CLAUDE.md item 8) even though the LLM is asked to switch to a coarser
  // one-node-per-module view above that threshold (see llm.ts's
  // COARSE_MODE_THRESHOLD). A reviewer scanning a big diagram should know
  // it's simplified by design, not missing detail by accident.
  const COMPLEXITY_NOTE_THRESHOLD = 6;
  const complexityNote =
    params.filesMatched !== undefined && params.filesMatched > COMPLEXITY_NOTE_THRESHOLD
      ? `\n\n> ℹ️ This PR touches ${params.filesMatched} files — the diagram groups related changes at the file/module level to stay readable, rather than showing every function individually. See the full diff for complete detail.\n`
      : "";

  // Self-identifying so the image still makes sense out of the PR-thread
  // context it was posted in (screenshotted into Slack, scrolled past a
  // long comment history) — a review caught that neither the image nor
  // the surrounding text said which PR or how much of it this covers.
  const context =
    params.prNumber !== undefined && params.filesMatched !== undefined
      ? ` · PR #${params.prNumber} · ${params.filesMatched} file${params.filesMatched === 1 ? "" : "s"} matched`
      : "";

  return `${ARCHLENS_MARKER}
### 🤖 Architecture Map — generated by ArchLens AI${context}

![Architecture diagram](${params.svgUrl})
${truncatedNote}${complexityNote}
<details>
<summary>Mermaid source</summary>

\`\`\`mermaid
${params.mermaidSource}
\`\`\`

</details>

*Visual Architecture Map Generated by [ArchLens AI](https://archlens.dev) · [Add ArchLens to your repo →](https://github.com/marketplace/actions/archlens-ai)*
`;
}

/**
 * Creates the ArchLens comment on first run, updates it in place on
 * subsequent pushes to the same PR. Returns the comment's HTML URL.
 */
export async function upsertComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  body: string
): Promise<string> {
  const comments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });

  const existing = comments.find((c) => c.body?.includes(ARCHLENS_MARKER));

  if (existing) {
    const { data } = await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
    return data.html_url;
  }

  const { data } = await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });
  return data.html_url;
}
